sudo: required
before_install:
  - sudo apt-get install make
  - sudo apt-get install g++
  - sudo apt-get install git
  - sudo apt-get install unzip
  - sudo apt-get install -y x11vnc xvfb libxcursor1 ca-certificates bzip2 libnss3 libegl1-mesa x11-xkb-utils libasound2
  - sudo update-ca-certificates
  - sudo apt-get install libglib2.0-0
  - sudo apt-get update
  
# Enable C++ support
language: cc

# Compiler selection
compiler:
  - gcc
  
install:
  - mkdir sinusbot
  - cd ./sinusbot
  - wget https://www.sinusbot.com/dl/sinusbot.current.tar.bz2
  - tar -xjf sinusbot.current.tar.bz2
  - wget https://raw.githubusercontent.com/VerHext/sinusbotTestSuite-storage/master/config.ini
  - wget https://github.com/VerHext/sinusbotTestSuite-storage/raw/master/TeamSpeak3-Client-linux_amd64.zip
  - unzip TeamSpeak3-Client-linux_amd64.zip
  - cp plugin/libsoundbot_plugin.so TeamSpeak3-Client-linux_amd64/plugins/
  - ls ../
  - echo "Starting Sinusbot" 
  - cp ../support-pp.js ./scripts/support-pp.js
  - ls
  - ./sinusbot
  

# Build steps
script:
  - sudo make -f make main
